#!/usr/bin/env bash

# Output current btp CLI context. Expects name of config file, defaults
# to value of $BTP_CLIENTCONFIG.

set -o errexit
set -o pipefail

getproperty() {

  # Retrieve value of property in the account config file. The
  # first leading period of the property name (from a jq perspective)
  # is optional.

  local file=$1
  local prop=$2

  [[ ! $prop =~ ^\. ]] && prop=".$prop"
  jq -r "$prop" "$file"

}

main() {

  # Show a short version of the context from the config file.

  local configfile="${1:-$BTP_CLIENTCONFIG}"
  local subdomain subaccount email

  subdomain="$(getproperty "$configfile" SubDomain)"
  subaccount="$(getproperty "$configfile" Subaccount)"
  email="$(getproperty "$configfile" Authentication.Mail)"

  if [[ $subaccount =~ ^$ ]]; then
    subaccount="(no subaccount targeted)"
  else
    subaccount="${subaccount:0:8}"
  fi

  echo "${email%%@*} / ${subdomain%-ga} / $subaccount"

}

main "$@"
