#!/usr/bin/env bash

# Output current btp CLI context. Expects name of config file, defaults
# to value of $BTP_CLIENTCONFIG.

set -o errexit
set -o pipefail

getcontext() {

  # A new version, based on what seems to be an updated structure
  # in the config file contents. Assuming for now that the entries
  # in the TargetHierarchy array are in some sort of meaningful order.
  local configfile=$1

  jq -r '
    [ .UserName | sub("@.+";"") ] + ( .TargetHierarchy | map(.DisplayName) )
    | join(" : ")
    ' "$configfile"

}

main() {

  # Show a short version of the context from the config file.
  getcontext "${1:-$BTP_CLIENTCONFIG}"

}

main "$@"
