#!/usr/bin/env bash

set -o errexit

# Logs the user in with the account specified.

# Store global account subdomain, user and password in pass store:
# - btp/<account>/subdomain (e.g. fffffffftrial-ga)
# - btp/<account>/user (e.g. qmacro+blue@gmail.com)
# - btp/<account>/password (e.g. sekrit)

declare URL="https://cpcli.cf.eu10.hana.ondemand.com"

main() {

  local account="${1:?No account specified}"

  # Cause script to abend if no account data stored
  pass "btp/$account" > /dev/null

  btp login \
    --url "$URL" \
    --user "$(pass "btp/$account/user")" \
    --subdomain "$(pass "btp/$account/subdomain")" \
    --password "$(pass "btp/$account/password")"

}

main "$@"
