#!/usr/bin/env bash

set -o errexit

# Logs the user in with the account specified.

# Store global account name and password in pass store:
# btp/<account>/ga (e.g. fffffffftrial)
# and btp/<account>/password (e.g. sekrit).

declare URL="https://cpcli.cf.eu10.hana.ondemand.com"

username() {

  local account=$1
  echo "qmacro+$account@gmail.com"

}

main() {

  local account="${1:?No account specified}"

  # Cause script to abend if no account data stored
  pass "btp/$account" > /dev/null

  btp login \
    --url "$URL" \
    --user "$(username "$account")" \
    --subdomain "$(pass "btp/$account/ga")-ga" \
    --password "$(pass "btp/$account/password")"

}

main "$@"
