#!/usr/bin/env bash

# Select subaccount of global account in btp. If there's only
# one, select it automatically. This used to then use 'btp target'
# to set the selected subaccount as the target for btp CLI. It
# doesn't, now.

set -o errexit
set -o pipefail

btp --format JSON list accounts/subaccount 2> /dev/null \
  | jq -r '.value[] | [.region, .displayName, .guid] | @tsv' \
  | fzf --with-nth=1,2 --exit-0 --select-1 \
  | cut -f 3
