#!/usr/bin/env bash

# Dotfiles setup - use after cloning dotfiles repo to .dotfiles

dotfiles="$HOME/dotfiles"

# Files
for i in inputrc gitconfig bashrc config/tmux/tmux.conf; do
  ln -s -f "$dotfiles/$i" "$HOME/.$i"
done
