#!/usr/bin/env bash

# Set up symbolic links - use after introducing dotfiles

dotfiles="$HOME/.dotfiles"

# Files
for i in inputrc vimrc tmux.conf gitconfig bashrc; do
  ln -s -f "$dotfiles/$i" "$HOME/.$i"
done

# Directories
ln -s -f "$dotfiles/bashrc.d" "$HOME/.bashrc.d"
