#!/usr/bin/env bash

# See https://unix.stackexchange.com/questions/450524/tmux-step-through-open-windows-automatically

readonly DELAY=5 # seconds

cycle() {

  local session=$1
  local lockfile="/tmp/tmux-cycle.$session"
  if [ -f "$lockfile" ]; then
    rm "$lockfile"
  else
    touch "$lockfile"
    while [ -f "$lockfile" ] && tmux next-window -t "$session"; do
      sleep "$DELAY"
    done
  fi

}

main() {

  cycle "${1:?Specify tmux session name}"

}

main "$@"
