#!/usr/bin/env bash

# Requests a fresh access token. Prepares the values required for this,
# i.e. the client_id and client_secret, the refresh_token, and the root of
# the API endpoint URL (to which, in this case, "/token" must be appended for
# such a token refresh call). Emits the refresh token to STDOUT.

# Requires a single parameter representing the "app" e.g. "yt" or "strava".
# Uses the 'refresh_token' script to actually make the call.

app="${1:?Specify app}"

readonly endpoint_root_var="OAUTH_ENDPOINT_ROOT_${app^^}"

OAUTH_CLIENT_ID=$(cat "$HOME/.oauth_${app}_client_id")
OAUTH_CLIENT_SECRET=$(cat "$HOME/.oauth_${app}_client_secret")
OAUTH_REFRESH_TOKEN=$(cat "$HOME/.oauth_${app}_refresh_token")
OAUTH_ENDPOINT_ROOT="${!endpoint_root_var}"

export OAUTH_CLIENT_ID OAUTH_CLIENT_SECRET OAUTH_REFRESH_TOKEN OAUTH_ENDPOINT_ROOT

./refresh_token
