#!/usr/bin/env bash

# Experimental App Studio setup script
# Invoke with curl github.com
set -o errexit

echo App Studio setup

# Bring in and set up dotfiles 
git clone https://github.com/qmacro/dotfiles.git .dotfiles
ln -s -f $HOME/.dotfiles/bashrc .bashrc

echo Done
