#!/usr/bin/env bash

# Experimental App Studio setup script
# Invoke with curl github.com
set -o errexit

declare dotfiles="$HOME/.dotfiles"
declare backupdir="$HOME/.appstudiosetup.backups"

backup() {
  if [[ -e "$HOME/$1" ]]; then
    local file="$(echo "$1" | tr '\/' '-')"
    cp "$HOME/$1" "$backupdir/$file"
  fi
}

[[ -d "$backupdir" ]] || mkdir "$backupdir"
backup ".bashrc"
backup ".theia/settings.json"

# Bring in and set up dotfiles 
rm -rf "$dotfiles"
git clone https://github.com/qmacro/dotfiles.git "$dotfiles"
ln -s -f "$dotfiles/bashrc" "$HOME/.bashrc"

# Configure dev space as I like it
cp "$dotfiles/.theia/settings.json" "$HOME/.theia/settings.json"

# Set up a common user-space bin directory for locally installed executables
mkdir "$HOME/bin"

# Install common utilities
curl -L https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 > "$HOME/bin/jq" && chmod +x "$HOME/bin/jq"
npm install --global jwt-cli

echo Done
