#!/usr/bin/env bash

# Sets a random theme every N minutes, via the excellent base16-shell
# (https://github.com/chriskempson/base16-shell) which you need to
# install first, obviously. After setting a new theme, it, the theme
# name is written to the tmux status bar (if tmux is running).

# Typical usage example for use in .bashrc - run in background and
# change theme every quarter of an hour:
#
# base16-shell-random 15 &

# DYNAMIC VALUES

# How often (in mins) to change the theme - supply as first argument
# on invocation, defaults to 30.
frequency=${1:-30}

# Where the theme scripts are (in the base16-shell installation)
themedir="${HOME}/.config/base16-shell/scripts"

# A couple of helper files - where we write the current theme
# and where we store the PID of this script when it's running.
scriptfilename=$(basename "$0")
themefile="/tmp/${scriptfilename}.theme"
pidfile="/tmp/${scriptfilename}.pid"


# FUNCTIONS

log () { echo "$(date '+%Y-%m-%d %H:%M:%S')" "$0"; }
err () { echo "$0" 1>&2; }

# Returns a truthy value if it's not time for another theme change
function not_time_yet {
  find "$themefile" -newermt "${frequency} mins ago" 2>/dev/null | \
    grep -q "$themefile"
}

# Pick a theme at random - returns the theme name
function pick_random_theme {
  local theme
  theme=$(find "$themedir" | sort -R | tail -1)
  basename "$theme" ".sh"
}

# Set the new theme, write the name to the themefile,
# and display the name in tmux (if running).
function set_theme {
  local theme=$1
  source "${themedir}/${theme}.sh"
  echo "$theme" > "$themefile"
  tmux rename-session "$theme" 2>/dev/null
}


# MAIN EXECUTION

# Check that another instance of this script isn't running,
# basing the check on whether the PID file exists or not.
if [[ -e $pidfile ]]; then
  err "Another instance of this script is already running"
  exit 2
fi

# Ensure PID file is removed on exit
trap "{ echo TRAP; rm -f $pidfile; }" EXIT SIGTERM

# Write PID to file
echo $$ > "$pidfile"

while true; do

  sleep 60

  # Go round again if it's not yet time to change the theme
  not_time_yet && continue

  theme=$(pick_random_theme)
  set_theme "$theme"

done
