#!/usr/bin/env bash

declare modelfile="${1:?Specify CDS model file to compile}"

declare scriptname="${0##*/}"
declare old="./.${scriptname}.old"
declare new="./.${scriptname}.new"

touch "$old"

cds compile --to yaml "$modelfile" > "$new"

bat -p -l yaml "$new"
echo
diff --color "$old" "$new"
cp "$new" "$old"
