#!/usr/bin/env bash

set -eo pipefail

declare model="${1:-srv/}"
declare myname="$(basename "$0")"

filter() {
  local match="c$"
  if [[ $myname =~ $match ]]; then
    bat --language sql --plain
  else
    cat
  fi
}

cds compile --to sql "$model" \
  | prettier --parser sql --print-width 60 \
  | filter
