#!/usr/bin/env bash

# getbtpcli - Get (latest) btp CLI

set -o errexit
declare -r licence="tools.hana.ondemand.com/developer-license-3_1.txt"

echo "Proceed (with Enter) only if you accept the SAP Developer Licence 3.1"
echo -n "(see $licence) ..."
read -r proceed

# Download tarball of latest version and unpack it
curl \
  --location \
  --header "Cookie: eula_3_1_agreed=$licence; path=/;" \
  "https://tools.hana.ondemand.com/additional/btp-cli-darwin-amd64-latest.tar.gz" \
  | tar \
    --extract \
    --strip-components 1 \
    --verbose \
    --gunzip \
    --file - \
    "darwin-amd64/btp"

# Remove any Apple quarantine
xattr -d com.apple.quarantine btp 2>/dev/null || true

# Get it to show the version
./btp --version
