#!/usr/bin/env bash

# Hidden user PWD - hpwd

# Shows the process working directory with the user's
# actual home directory hidden and substituted with ~.

# Optionally takes a single parameter that is the dir.

echo "${1:-$PWD}" | sed 's@^'"$HOME"'@~@'
