#!/usr/bin/env bash

# When in a repo directory, gives an overview of open issues.
# Optional single arg: one or more labels, comma-separated (no spaces)

# Invocation examples:
# issues
# issues cross-team-issue
# issues cross-team-issue,important

set -o errexit

# Load common functions
readonly here="$(dirname "$0")"
source "$here/github.sh"

jqscript() {

  cat << EOF
  .[]
  | [
    .number,
    .title,
    "\(.title)\n\n\(.body)\n\nUser: \(.user.login)"
    ]
  | @tsv
EOF

}

main() {

  abort_if_not_repo

  local labels hostname
  labels=${1:+labels=${1}}
  hostname=$(get_hostname)

  gh api \
    "/repos/:owner/:repo/issues?${labels}" \
    --hostname "$hostname" \
    --paginate \
    --cache 10m \
    --jq "$(jqscript)" \
    | fzf \
      --with-nth=1,2 \
      --delimiter='\t' \
      --preview='echo -e {3}' \
      --preview-window="$(preview_window_location):wrap" \
    | cut -f 1

}

main "$@"
