#!/usr/bin/env bash

repo=qmacro.github.io
clone_location="${BLOG_REPO_LOCATION:-$HOME/Projects}/$repo"

source utils # err

makename() {
  echo "$@" \
    | tr "[:upper:]" "[:lower:]" \
    | tr "[:blank:]" -
}

# MAIN

# Abort if we haven't been given any title
[[ $# -eq 0 ]] && err "No title supplied" && exit 1

postdate=$(date "+%Y-%m-%d")
posttime=$(date "+%H:%M:%S")
postname=$(makename "$@")

cd "$clone_location" || exit
filename="_posts/$postdate-$postname.markdown"
cat > "$filename" << EOF
---
layout: post
title: $@
date: '$postdate $posttime'
---

_The lede_
EOF

$EDITOR "$filename"
