#!/usr/bin/env bash

# Create new Bash shell script - newscript

declare script=$1
if [[ ! -f "$script" ]]; then
  cat > "$script" << EOF
#!/usr/bin/env bash

set -eo pipefail

somefunction() {

  :

}

main() {

  somefunction

}

main "\$@"
EOF
  chmod +x "$script"
fi

"$EDITOR" "$script"
