#!/usr/bin/env bash

# Only proceed if we have GLOACCUSR defined
# (signifying this is a Feature Set B user)
[ -z ${GLOACCUSR} ] && exit 1

# Sets sapcp target according to env vars
sapcp login \
  --url ${CLISRVURL} \
  --subdomain ${GLOACCSDM} \
  --user ${GLOACCUSR}

# Offers the subaccount list to pick from
subaccount=$(
sapcp list accounts/subaccount 2>/dev/null \
 | sed -E '1,4d;/^\s*$/d' \
 | fzf --prompt 'Select subaccount' \
 | awk '{print $1}'
 )

if [ ! -z ${subaccount} ]; then
  sapcp target --subaccount ${subaccount}
fi
