#!/usr/bin/env bash

# Takes owner/repo/path and shows content of that resource from GitHub.
# Assumes there's an extension on the resource name (e.g. yml) and uses
# that for the value of bat's --language parameter.

declare owner=$1
declare repo=$2
declare path=$3
declare language="${4:-txt}"
declare color="${5:-never}"

gh api \
  --cache "${GH_CACHETIME:-1h}" \
  --jq '.content' \
  "/repos/$owner/$repo/contents/$path" \
  | base64 --decode -i - \
  | bat --color "$color" --theme gruvbox --plain --language "$language" -
