#!/usr/bin/env bash

# Wrapper around ijq to capture the actual jq expression that was used, 
# unless it ended in an error. The capture of the expression is into a 
# TMUX paste buffer, so this will only be valid in a TMUX session.

# Just exec ijq directly if we're not in a TMUX context
[[ -z $TMUX ]] && exec ijq "$@"

# This is a temporary file to capture the jq expression in
declare tempfile
tempfile="$(mktemp)"

# When ijq ends, the output of the expression is emitted to STDOUT,
# and the expression itself is output to STDERR.

# Run ijq and capture STDERR and the actual RC
declare ijqrc
ijq "$@" 2>"$tempfile"
ijqrc="$?"

# Either things were OK, in which case set the TMUX paste buffer.
# Otherwise, emit the error and also pass on the error RC.
if [[ "$ijqrc" -eq 0 ]]; then
  tmux set-buffer "$(cat "$tempfile")"
else
  cat "$tempfile"
  exit "$ijqrc"
fi
