#!/usr/bin/env bash

declare CONNAME=dev
declare HOMELOC=$HOME

docker container rm "$CONNAME" 2> /dev/null
docker container run \
  --volume "$HOMELOC/.ssh":/home/user/.ssh \
  --volume "$HOMELOC/.gnupg":/home/user/.gnupg \
  --volume "$HOMELOC/.steampipe":/home/user/.steampipe \
  --volume "$HOMELOC/.password-store":/home/user/.password-store \
  --volume "$HOMELOC/.config":/home/user/.config \
  --volume "$HOMELOC/onedrive":/home/user/work \
  --name "$CONNAME" \
  --interactive \
  --tty \
  devtainer
