#!/usr/bin/env bash

declare CONNAME=dev
declare HOMELOC=/var/services/homes

docker run \
  --volume "$HOMELOC/dj/.ssh":/home/user/.ssh \
  --volume "$HOMELOC/dj/.gnupg":/home/user/.gnupg \
  --volume "$HOMELOC/dj/.password-store":/home/user/.password-store \
  --volume "$HOMELOC/dj/.config/gh":/home/user/work/.config/gh \
  --volume "$HOMELOC/dj/work":/home/user/work \
  --name "$CONNAME" \
  --interactive \
  --tty \
  devtainer
