#!/usr/bin/env bash

declare CONNAME=dev
declare HOMELOC=$HOME

docker context use default
docker container rm "$CONNAME" 2> /dev/null
docker container run \
  --volume "$HOMELOC/.ssh":/home/user/.ssh \
  --volume "$HOMELOC/.gnupg":/home/user/.gnupg \
  --volume "$HOMELOC/.steampipe":/home/user/.steampipe \
  --volume "$HOMELOC/.password-store":/home/user/.password-store \
  --volume "$HOMELOC/.config":/home/user/.config \
  --volume "$HOMELOC/work":/home/user/work \
  --platform linux/amd64 \
  --publish 4004:4004 \
  --publish 8000:8000 \
  --name "$CONNAME" \
  --interactive \
  --tty \
  devcontainer
